theme: jekyll-theme-minimal
title: Scraping Garden Party
description: A small site based on the short story collection _The Garden Party: and Other Stories_ by Katherine Mansfield, built for a web scraping exercise for students at the University of Canterbury
logo: assets/images/katherine-mansfield.jpg
